//
//  SettingsEntry.swift
//  SharedSettings
//
//  A type-erased view of one setting, so a screen can list settings it doesn't know statically.
//

import SwiftUI

/// One registered setting, erased so a catalog can hold a mixed-payload list.
///
/// Reads and writes go through ``ObservedSettings`` so a SwiftUI view listing entries
/// refreshes when any of them changes.
public struct SettingsEntry: Identifiable, Sendable {
	/// The storage key name — unique across namespaces.
	public let id: String
	/// A human-readable title derived from the declaration (`useStagingAPI` → "Use Staging API").
	public let title: String
	public let kind: SettingsKind

	/// `.buildTime` settings are baked in and can only be displayed.
	public var isEditable: Bool { kind != .buildTime }

	let read: @MainActor @Sendable () -> any Sendable
	let write: @MainActor @Sendable (any Sendable) -> Void

	@MainActor public var value: any Sendable { read() }

	/// The current value if it's a `T`, otherwise nil. Used to pick a control for the entry.
	@MainActor public func value<T: Sendable>(as type: T.Type) -> T? { read() as? T }

	/// A binding to the value as a `T`, falling back to `fallback` if the payload isn't a `T`.
	@MainActor public func binding<T: Sendable>(_ type: T.Type, fallback: T) -> Binding<T> {
		Binding { read() as? T ?? fallback } set: { write($0) }
	}

	@MainActor public var displayValue: String { String(describing: read()) }
}

public extension SettingsKey {
	/// Erases this key into a catalog entry. Generated by the settings-namespace macros.
	nonisolated static func entry(title: String) -> SettingsEntry {
		SettingsEntry(
			id: name,
			title: title,
			kind: kind,
			read: { ObservedSettings.instance[Self.self] ?? defaultValue },
			write: { newValue in
				guard let payload = newValue as? Payload else { return }
				ObservedSettings.instance[Self.self] = payload
			}
		)
	}
}

/// A group of settings declared together, so a screen can list them without runtime type discovery.
///
/// Conformance is generated by `@UserSettings`, `@DeveloperSettings`, and `@BuildSettings`.
public protocol SettingsNamespace {
	static var allSettings: [SettingsEntry] { get }
}
